version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080" # Exposer le port 8080 pour l'application
    depends_on:
      - db # Assurer que le conteneur db démarre avant
    environment:
      DB_URL: jdbc:mysql://db:3306/gestionpresence
      DB_USERNAME: root
      DB_PASSWORD: motdepasse # Remplacer par un mot de passe sécurisé

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: motdepasse # Mot de passe root pour MySQL
      MYSQL_DATABASE: gestionpresence # Base de données initiale
    ports:
      - "3306:3306" # Exposer le port 3306 pour MySQL
    volumes:
      - db_data:/var/lib/mysql # Sauvegarder les données MySQL dans un volume

volumes:
  db_data: # Définir un volume pour persister les données MySQL
